import 'package:flutter/material.dart';

 String logo = "assets/App_images/iedclogo.png";
 String flower = "assets/App_images/flower.png";
String grp1 = "assets/App_images/grp1.jpg";
String lab = "assets/App_images/lab.jpg";
String lap = "assets/App_images/lap.jpg";
String flu = "assets/App_images/flu.jpg";
String lab3= "assets/App_images/lab3.jpg";
String visionn= "assets/App_images/visionn.jpg";
String mission= "assets/App_images/mission.jpg";
String vision= "assets/App_images/vision.jpg";
String idea= "assets/App_images/idea.jpeg";
String cert= "assets/App_images/cert.jpg";
String poster3= "assets/App_images/poster3.jpeg";
String poster4= "assets/App_images/poster4.png";
String poster5= "assets/App_images/poster5.jpeg";
String poster6= "assets/App_images/poster6.jpeg";
String Trainthetrainers= "assets/App_images/Trainthetrainers.jpeg";
String download= "assets/App_images/download.jpeg";